### ISSUE TITLE
你明明用的是tensorflow1.6，非要写什么pytorch1.6，你他娘还真是个人才。

### ISSUE THREAD

**Issue by lijianjing** [ShihanYang/UKGsE#1]
keras作为高层接口，后端引擎使用TensorFlow，Theano，或者 CNTK，没有pytorch。

**Comment by ShihanYang** [comment]
Shit, you are weird. anyway, thanks.

**Comment by lijianjing** [comment]
不好意思，我爆粗口了，非常抱歉，诚挚向您道歉！
